tweet/urls.py
from django.urls import path
from . import views

app_name = "tweet"

urlpatterns = [ 
    path('', views.tweet_list, name = 'tweet_list'),
    path('create/', views.tweet_create, name = 'tweet_create'),
    path('<int:tweet_id>/edit/', views.tweet_edit, name = 'tweet_edit'),
    path('<int:tweet_id>/delete/', views.tweet_delete, name = 'tweet_delete'),
    path('register/', views.user_register, name = 'register'),
    path('search/', views.searching, name = 'search'),
    path('<int:tweet_id>/detail/', views.tweet_detail, name = 'tweet_detail')
] 

tweetsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.urls import views as auth_views
urlpatterns = [
    path('', include('tweet.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tweet/models.py
from django.db import models
from django.contrib.auth.models import User

class Tweet(models.Model):
    #To tweets only from the registered users foreign key is used 
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(max_length=400)
    photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    created_at =  models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.user.username} - {self.text[:20]}'
     

tweet/forms.py
from django import forms
from .models import Tweet
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

"""To use django provided fields for model."""

class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ['text', 'photo']
    
class UserRegisterationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

tweet/views.py
from django.shortcuts import render
from .models import Tweet
from .forms import TweetForm, UserRegisterationForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.db.models import Q

def tweet_list(request):
    tweets = Tweet.objects.all().order_by("created_at")[:20]
    return render(request, 'tweet/tweet_list.html', {'tweets': tweets})


@login_required
def tweet_create(request):
    #Either form is filled or not 
    if request.method == "POST":
        form = TweetForm(request.POST, request.FILES)
        if form.is_valid():
            tweet = form.save(commit = False)
            tweet.user = request.user
            tweet.save() 
            return redirect('tweet:tweet_list')
    else:
        form = TweetForm()
        
    return render(request, 'tweet/tweet_form.html', {'form' : form})


@login_required        
def tweet_edit(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk = tweet_id, user = request.user)
    if request.method == "POST":
        #Instance get the tweet which we are editing as we get at the top
        form = TweetForm(request.POST, request.FILES, instance = tweet)
        if form.is_valid():
            tweet = form.save(commit = False)
            tweet.user = request.user
            tweet.save()
            return redirect('tweet:tweet_list')
    else:
        form = TweetForm(instance = tweet)
        
    return render(request, 'tweet/tweet_form.html', {'form' : form})


@login_required    
def tweet_delete(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk = tweet_id, user = request.user)
    if request.method == 'POST':
        tweet.delete()
        return redirect('tweet:tweet_list')
    return render(request, 'tweet/tweet_confirm_delete.html', {'tweet' : tweet})


def user_register(request):
    if request.method == 'POST':
        form = UserRegisterationForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            return redirect('tweet:tweet_list')
    else:
        form = UserRegisterationForm()
    return render(request, 'registration/register.html', {'form' : form})

def searching(request):
    query = request.GET.get('query')
    result = Tweet.objects.filter(Q(user__username__icontains = query) | Q(text__icontains = query))
    return render(request, 'tweet/tweet_list.html',{'tweets':result})    

def tweet_detail(request, tweet_id):
    tweet = get_object_or_404(Tweet, pk = tweet_id)
    return render(request, 'tweet/tweet_detail.html', {'tweet':tweet})

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <title>
        {% block title %}
        title default
        {% endblock %}
    </title>

</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'tweet:tweet_list' %}">Tweets</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'tweet:tweet_list' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'tweet:tweet_list' %}">Link</a>
          </li>
        </ul>
        <form class="d-flex mx-auto" method="get" action = {% url 'tweet:search' %}>
          <input class="form-control me-2" name="query" style="width:300px; padding:6px; padding-left:15px" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-light d-flex align-items-center" type="submit">
            <span class="fa fa-search" style="margin-right: 5px;"></span>
            <span>Search</span>
          </button>
        </form>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <form method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button class="btn btn-danger mx-2" type="submit">
                  <span class="fas fa-power-off"></span>
                  <span class="mt-2">Logout</span>
                </button>
              </form>
            </li>
          {% else %}
            <li class="nav-item">
              <a href="{% url 'tweet:register' %}" class="btn btn-secondary mx-2">
                <span class="fas fa-list-alt"></span>
                <span class="mt-2">Register</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'login' %}" class="btn btn-success mx-2">
                <span class="fa fa-user"></span>
                <span class="mt-2 p-2">Login</span>
              </a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    This is layout page
    {% endblock %}
  </div>
</body>
</html>

tweet/templates/tweet/tweet_confirm_delete.html
{% extends 'layout.html' %}

{% block title %}
    tweet
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card bg-dark text-white">
                <div class="card-body">
                    <h3 class="text-center mt-4">Are you sure you want to delete the tweet?</h3>
                    <form method="post">
                        {% csrf_token %}
                        <button class="btn btn-danger mt-3">Delete</button>
                        <a class="btn btn-light mt-3 ml-2" href="{% url 'tweet:tweet_list' %}">Cancel</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

tweet/templates/tweet/tweet_detail.html
{% extends 'layout.html' %}

{% block title %}
    tweet
{% endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card p-3 shadow-sm" style="border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
                    <div class="row no-gutters">
                        <div class="col-md-5">
                            <div class="card-body">
                                <h4 class="card-title">
                                    <span class="fa fa-user-circle" style="margin-right: 10px;"></span>{{ tweet.user.username }}
                                </h4>
                                <p class="card-text">{{ tweet.text }}</p>
                            </div>
                        </div>
                        <div class="col-md-7 d-flex justify-content-center align-items-center">
                            <img src="{{ tweet.photo.url }}" class="img-fluid" alt="Profile photo" style="border-radius: 8px;">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

tweet/templates/tweet/tweet_form.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block title %}
    tweet
{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <h2 class="text-center mb-4">
                        {% if form.instance.pk %}
                            Edit Tweet
                        {% else %}
                            Create Tweet            
                        {% endif %}
                    </h2>
                    <form method="POST" enctype="multipart/form-data" class="form">
                        {% csrf_token %}
                        {% render_field form.text placeholder="Enter Description" class+="form-control mb-3" %}
                        {% render_field form.photo class+="form-control mb-3" %}
                        {% if form.errors %}
                            <div class="alert alert-danger mt-3">
                                <strong>Error!</strong> Please correct the errors below.
                            </div>
                        {% endif %}
                        <div class="text-center">
                            <button type="submit" class="btn btn-success mx-2 px-5 ">Submit</button>
                            <a href="{% url 'tweet:tweet_list' %}" class="btn btn-secondary mx-2 px-5">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

tweet/templates/tweet/tweet_list.html
{% extends 'layout.html' %}

{% block title %}
    Tweet
{% endblock title %}

{% block content %}
    <style>
        .animated-card {
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }

        .animated-card:hover {
            transform: translateY(-20px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }
    </style>
    
    <h1 class="text-center text-white mt-4">Welcome to Tweets App</h1>
    <a class="btn btn-light m-4 mt-4" href="{% url 'tweet:tweet_create' %}">Create Tweet</a>
    <div class="container d-flex flex-wrap mt-3">
        {% for tweet in tweets %}
            <a href="{% url 'tweet:tweet_detail' tweet.id %}" style="text-decoration: none; color: inherit;">
                <div class="card animated-card" style="width: 18rem; height: 350px; margin: 15px;">
                    <img src="{{ tweet.photo.url }}" class="card-img-top" style="height: 200px; object-fit: cover;" alt="Profile photo">
                    <div class="card-body d-flex flex-column">
                        <h5 class="card-title">{{ tweet.user.username }}</h5>
                        <p class="card-text" style="flex-grow: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">{{ tweet.text|slice:":60" }}
                            {% if tweet.text|length > 60 %}...{% endif %}
                        </p>
                        {% if tweet.user == user %}
                            <div class="mt-4">
                                <a href="{% url 'tweet:tweet_edit' tweet.id %}" class="btn btn-light btn-sm">
                                    <span style="margin-right:5px">Edit</span>
                                    <span class="fa fa-edit"></span>
                                </a>          
                                <a href="{% url 'tweet:tweet_delete' tweet.id %}" class="btn btn-danger btn-sm">
                                    <span>Delete</span>
                                    <span class="fa fa-trash"></span>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock content %}